import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'prussian-blue': '#003153',
        'midnight-blue': '#001D34',
        'vibrant-saffron': '#ff8800',
        'deep-saffron': '#cc6d00',
        'crisp-green': '#1B6D24',

        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',

        'on-surface': '#1a1c1c',
        'on-surface-variant': '#42474e',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',

        'outline': '#73777f',
        'outline-variant': '#c2c7cf',

        'primary': '#001c32',
        'on-primary': '#ffffff',
        'primary-container': '#003153',
        'on-primary-container': '#759ac1',
        'primary-fixed': '#d0e4ff',
        'primary-fixed-dim': '#a5caf4',
        'on-primary-fixed': '#001d34',
        'on-primary-fixed-variant': '#22496c',
        'surface-tint': '#3c6186',

        'secondary': '#755b00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fccc38',
        'on-secondary-container': '#6f5600',
        'secondary-fixed': '#ffdf90',
        'secondary-fixed-dim': '#f0c12c',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',

        'tertiary': '#002003',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003809',
        'on-tertiary-container': '#58a857',
        'tertiary-fixed': '#a3f69c',
        'tertiary-fixed-dim': '#87d982',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
      },
      fontFamily: {
        sans: ['Montserrat', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'label-md': ['Montserrat', 'sans-serif'],
        'caption': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      spacing: {
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        'gutter': '1.5rem',
        'stack-xs': '0.25rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
        'stack-xl': '4rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'hard': '4px 4px 0px 0px #003153',
        'hard-saffron': '4px 4px 0px 0px #ff8800',
        'hard-crisp': '4px 4px 0px 0px #1B6D24',
        'hard-sm': '2px 2px 0px 0px #003153',
      },
    },
  },
  plugins: [],
}

export default config
